# Generated by Django 4.1.1 on 2022-10-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='O título da atividade', max_length=255)),
                ('template_image', models.ImageField(height_field='height', help_text='A imagem que será usada para definir os campos', upload_to='templates', width_field='width')),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem template', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem template', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(help_text='Um identificador único do aluno dessa entrega', max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height', help_text='A imagem da atividade', null=True, upload_to='submissions', width_field='width')),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem', null=True)),
                ('assignment', models.ForeignKey(help_text='A atividade da qual a entrega faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='auxilioavaliacao.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='O nome do campo', max_length=50)),
                ('points', models.IntegerField(default=0, help_text='A nota dessa questão')),
                ('image', models.ImageField(blank=True, help_text='A imagem do campo', null=True, upload_to='fields')),
                ('x', models.IntegerField(help_text='A coordenada X do ponto esquerdo superior em referência a imagem da entrega')),
                ('y', models.IntegerField(help_text='A coordenada Y do ponto esquerdo superior em referência a imagem da entrega')),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem do campo', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem do campo', null=True)),
                ('assignment', models.ForeignKey(help_text='A atividade de qual o campo faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='auxilioavaliacao.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Um curto descritor do agrupamento (por exemplo, o conteúdo das respostas)', max_length=30)),
                ('points', models.IntegerField(blank=True, default=0, help_text='A nota dessa resposta')),
                ('feedback', models.CharField(blank=True, default='', help_text='Um comentário a respeito da resposta', max_length=500)),
                ('field', models.ForeignKey(help_text='O campo das respostas agrupadas neste grupo', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auxilioavaliacao.field')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, help_text='A nota dessa resposta')),
                ('feedback', models.CharField(blank=True, default='', help_text='Um comentário a respeito da resposta', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, help_text='A imagem da resposta', null=True, upload_to='submissionFields')),
                ('x', models.IntegerField(blank=True, help_text='A coordenada X do ponto esquerdo superior em referência a imagem da entrega', null=True)),
                ('y', models.IntegerField(blank=True, help_text='A coordenada Y do ponto esquerdo superior em referência a imagem da entrega', null=True)),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem da resposta', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem da resposta', null=True)),
                ('modified', models.BooleanField(default=False, help_text='Se a região da resposta foi alterada da padrão')),
                ('field', models.ForeignKey(help_text='O campo desta resposta', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auxilioavaliacao.field')),
                ('group', models.ForeignKey(blank=True, help_text='O grupo que esta resposta faz parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='auxilioavaliacao.answergroup')),
                ('submission', models.ForeignKey(help_text='A entrega da qual essa resposta faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auxilioavaliacao.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(models.F('assignment'), models.F('studentId'), name='unique_student_submission_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='answergroup',
            constraint=models.UniqueConstraint(models.F('field'), models.F('name'), name='unique_group_name_per_field'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(models.F('submission'), models.F('field'), name='unique_field_per_submission'),
        ),
    ]
