# Generated by Django 4.1.1 on 2022-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
