# Generated by Django 4.1.1 on 2023-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.FloatField(default=0, help_text='A nota dessa resposta'),
        ),
        migrations.AlterField(
            model_name='answergroup',
            name='points',
            field=models.FloatField(blank=True, default=0, help_text='A nota dessa resposta'),
        ),
        migrations.AlterField(
            model_name='field',
            name='points',
            field=models.FloatField(default=0, help_text='A nota dessa questão'),
        ),
    ]
