# Generated by Django 4.1.1 on 2023-04-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0002_alter_answer_points_alter_answergroup_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergroup',
            name='name',
            field=models.CharField(help_text='Um curto descritor do agrupamento (por exemplo, o conteúdo das respostas)', max_length=1000),
        ),
    ]
