# Generated by Django 4.1.1 on 2022-09-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0002_alter_imagem_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Regiao',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='imagem',
            new_name='image',
        ),
    ]
