# Generated by Django 4.1.1 on 2022-09-19 19:48

import auxilioavaliacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0003_rename_imagem_image_rename_regiao_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=auxilioavaliacao.models.image_directory_path),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
