# Generated by Django 4.1.1 on 2022-09-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0004_remove_image_image_image_file_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
