# Generated by Django 4.1.1 on 2022-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0005_alter_region_height_alter_region_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='height',
        ),
        migrations.RemoveField(
            model_name='region',
            name='width',
        ),
        migrations.RemoveField(
            model_name='region',
            name='x',
        ),
        migrations.RemoveField(
            model_name='region',
            name='y',
        ),
        migrations.AddField(
            model_name='region',
            name='x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='x2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='y2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
