# Generated by Django 4.1.1 on 2022-09-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0006_remove_region_height_remove_region_width_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='image',
            new_name='from_image',
        ),
    ]
