# Generated by Django 4.1.1 on 2022-09-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0008_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='regions'),
        ),
    ]
