# Generated by Django 4.1.1 on 2022-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0009_region_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images', width_field='width'),
        ),
    ]
