# Generated by Django 4.1.1 on 2022-09-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0011_alter_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='A imagem da resposta', null=True, upload_to='submissionFields')),
                ('x1', models.IntegerField(blank=True, help_text='A coordenada X do ponto esquerdo superior em referência a imagem da entrega', null=True)),
                ('y1', models.IntegerField(blank=True, help_text='A coordenada Y do ponto esquerdo superior em referência a imagem da entrega', null=True)),
                ('x2', models.IntegerField(blank=True, help_text='A coordenada X do ponto direito inferior em referência a imagem da entrega', null=True)),
                ('y2', models.IntegerField(blank=True, help_text='A coordenada Y do ponto direito inferior em referência a imagem da entrega', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='O título da atividade', max_length=255)),
                ('template_image', models.ImageField(height_field='height', help_text='A imagem que será usada para definir os campos', upload_to='templates', width_field='width')),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem template', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem template', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='O nome do campo', max_length=50)),
                ('x1', models.IntegerField(help_text='A coordenada X do ponto esquerdo superior em referência a imagem da entrega')),
                ('y1', models.IntegerField(help_text='A coordenada Y do ponto esquerdo superior em referência a imagem da entrega')),
                ('x2', models.IntegerField(help_text='A coordenada X do ponto direito inferior em referência a imagem da entrega')),
                ('y2', models.IntegerField(help_text='A coordenada Y do ponto direito inferior em referência a imagem da entrega')),
                ('pctX1', models.FloatField(blank=True, help_text='O percentual do ponto esquerdo superior em relação a largura da imagem template', null=True)),
                ('pctY1', models.FloatField(blank=True, help_text='O percentual do ponto esquerdo superior em relação a altura da imagem template', null=True)),
                ('pctX2', models.FloatField(blank=True, help_text='O percentual do ponto direito inferior em relação a largura da imagem template', null=True)),
                ('pctY2', models.FloatField(blank=True, help_text='O percentual do ponto direito inferior em relação a altura da imagem template', null=True)),
                ('assignment', models.ForeignKey(help_text='A atividade de qual o campo faz parte', on_delete=django.db.models.deletion.CASCADE, to='auxilioavaliacao.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(help_text='Um identificador único do aluno dessa entrega', max_length=255)),
                ('image', models.ImageField(blank=True, height_field='height', help_text='A imagem da atividade', null=True, upload_to='submissions', width_field='width')),
                ('width', models.IntegerField(blank=True, help_text='A largura da imagem', null=True)),
                ('height', models.IntegerField(blank=True, help_text='A altura da imagem', null=True)),
                ('assignment', models.ForeignKey(help_text='A atividade da qual a entrega faz parte', on_delete=django.db.models.deletion.CASCADE, to='auxilioavaliacao.assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='from_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(help_text='O campo desta resposta', on_delete=django.db.models.deletion.CASCADE, to='auxilioavaliacao.field'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(help_text='A entrega da qual essa resposta faz parte', on_delete=django.db.models.deletion.CASCADE, to='auxilioavaliacao.submission'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(models.F('assignment'), models.F('studentId'), name='unique_student_submission_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(models.F('submission'), models.F('field'), name='unique_field_per_submission'),
        ),
    ]
