# Generated by Django 4.1.1 on 2022-09-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0012_answer_assignment_field_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='height',
            field=models.IntegerField(blank=True, help_text='A altura da imagem do campo', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, height_field='height', help_text='A imagem do campo', null=True, upload_to='', verbose_name='fields', width_field='width'),
        ),
        migrations.AddField(
            model_name='field',
            name='width',
            field=models.IntegerField(blank=True, help_text='A largura da imagem do campo', null=True),
        ),
    ]
