# Generated by Django 4.1.1 on 2022-09-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0013_field_height_field_image_field_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, height_field='height', help_text='A imagem do campo', null=True, upload_to='fields', width_field='width'),
        ),
    ]
