# Generated by Django 4.1.1 on 2022-09-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0014_alter_field_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(help_text='A atividade da qual a entrega faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='auxilioavaliacao.assignment'),
        ),
    ]
