# Generated by Django 4.1.1 on 2022-09-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0015_alter_submission_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='field',
            field=models.ForeignKey(help_text='O campo desta resposta', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auxilioavaliacao.field'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(help_text='A entrega da qual essa resposta faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auxilioavaliacao.submission'),
        ),
        migrations.AlterField(
            model_name='field',
            name='assignment',
            field=models.ForeignKey(help_text='A atividade de qual o campo faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='auxilioavaliacao.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(help_text='A atividade da qual a entrega faz parte', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='auxilioavaliacao.assignment'),
        ),
    ]
