# Generated by Django 4.1.1 on 2022-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0016_alter_answer_field_alter_answer_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='x1',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='y1',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='x1',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='y1',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='y2',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pctX1',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pctX2',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pctY1',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pctY2',
        ),
        migrations.RemoveField(
            model_name='field',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='field',
            name='y2',
        ),
        migrations.AddField(
            model_name='answer',
            name='height',
            field=models.IntegerField(blank=True, help_text='A altura da imagem da resposta', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='width',
            field=models.IntegerField(blank=True, help_text='A largura da imagem da resposta', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, help_text='A imagem do campo', null=True, upload_to='fields'),
        ),
    ]
