# Generated by Django 4.1.1 on 2022-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0017_rename_x1_answer_x_rename_y1_answer_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified',
            field=models.BooleanField(default=False, help_text='Se a região da resposta foi alterada da padrão'),
        ),
    ]
