# Generated by Django 4.1.1 on 2022-10-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0018_answer_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(help_text='O campo das respostas agrupadas neste grupo', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='auxilioavaliacao.field')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(blank=True, help_text='O grupo que está resposta faz parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='auxilioavaliacao.answergroup'),
        ),
    ]
