# Generated by Django 4.1.1 on 2022-10-11 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxilioavaliacao', '0019_answergroup_answer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='answergroup',
            name='name',
            field=models.CharField(default='', help_text='Um curto descritor do agrupamento (por exemplo, o conteúdo das respostas)', max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='group',
            field=models.ForeignKey(blank=True, help_text='O grupo que esta resposta faz parte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='auxilioavaliacao.answergroup'),
        ),
        migrations.AddConstraint(
            model_name='answergroup',
            constraint=models.UniqueConstraint(models.F('field'), models.F('name'), name='unique_group_name_per_field'),
        ),
    ]
